/* Database schema to keep the structure of entire database. */


CREATE TABLE animals(
   id INT GENERATED BY DEFAULT AS IDENTITY,
   name VARCHAR NOT NULL,
   date_of_birth DATE,
   escape_attempts INT,
   neutered BOOL,
   weight_kg DECIMAL(5,2)
);

ALTER TABLE animals ADD species VARCHAR;

CREATE TABLE owners(
   id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   full_name VARCHAR NOT NULL,
   age INT);

CREATE TABLE species(
   id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
   name VARCHAR NOT NULL);

ALTER TABLE animals ADD PRIMARY KEY(id);
ALTER TABLE animals ADD COLUMN species_id INT REFERENCES species(id);
ALTER TABLE animals ADD COLUMN owner_id INT REFERENCES owners(id);

